= What I Use
D10f <devontheroof@pm.me>
v1, 2024-06-28
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:description: The software I use, how and why.
:keywords: technology software stack programming tools editor
:source-highlighter: pygments
:icons: font
:toc:

This is what I use every day to get things done. You can https://codeberg.org/d10f/dotfiles[checkout my dot files] to see how I configure some of the software listed below.

== Operating System

=== Debian

One of the oldest GNU/Linux distributions, well-known for its stability and reliability. I use this in both servers and desktop computers.

https://debian.org

== Desktop Environment

=== XFCE

A fast and lightweight environment that's easy to use. It embodies the traditional Unix philosophy of modularity, making it very simple to customize and combine with other components. For example, I use it along the `i3` window manager to have the best of both worlds.

https://xfce.org

== Window Managers

=== i3

Most tiling window managers are designed around keyboard workflows, but `i3` has excellent support for mouse actions right out of the box. It's intentionally designed to be simple, which makes it easy to customize and work with. Also, it can be integrated with XFCE very easily.

https://i3wm.org

== Terminal Emulator

=== Alacritty

Currently, my favorite terminal emulator. It's fast, extremely easy to configure using a plain text file, with tons of configuration options.

https://alacritty.org

== Web Browser

=== Mozilla Firefox

Mozilla Firefox remains one of the few browsers that has plenty of configuration options. One of my favorite features is the ability to customize the interface, using simple CSS rules, and even apply custom styles to websites directly.

https://www.mozilla.org/firefox

=== Librewolf

The privacy-focused fork of Mozilla Firefox. It comes out of the box with a lot of configurations that increase your privacy. Some websites might not work because of this, however, but it's otherwise identical to Firefox in most regards.

https://librewolf.net

=== Brave Browser

My go-to Chromium-based browser. It's easy to set up and to maintain while most non-desirable features are opt-in by default &mdash; a fairly rare sight these days.

https://brave.com

=== Vivaldi

Another excellent Chromium-based browser that's known for its highly customization capabilities.

https://vivaldi.net

== Text Editor & IDE

=== Vi

While I generally prefer more feature-rich editors, `vi` is usually found in most Linux distributions, including extremely bare installations where no display software is available, such as servers and containers.

=== Neovim

A very popular fork of Vim made with fantastic modular capabilities. Can be turned into an efficient tool for taking notes, editing files or a full-blown IDE.

https://neovim.io

=== VSCodium

Free and open source version of Microsoft's VSCode. Works exactly the same but has Microsoft's blobs and tracking/telemetry removed.

https://vscodium.com

== Color Schemes

=== Catppuccin

You are seeing it in action right now! Check out the button on the right inside the navigation bar.

https://github.com/catppuccin

=== Everforest

Another color scheme that I really like and that I've included in this website. Dark, but not too dark, and with pleasant green tones that are very easy on the eyes even on low light conditions.

https://github.com/sainnhe/everforest

=== Monokai Pro

I prefer the Catppuccin theme for most things, including the terminal and terminal-based programs since they blend nicely this way. However, for VSCodium I really like Monokai Pro because of the colors and icons.

https://monokai.pro

== File Sharing

=== Syncthing

Quite the handy tool to keep files in sync, both over a local network and remotely, over the internet. Among its many features it has encryption for safe transmission over relays, versioning, integrity checks, compression, etc.

https://syncthing.net

=== Send

Ever since Mozilla discontinued its own file sharing service, multiple other open-source projects have appeared to fill the gap. Some of them are new implementations designed from the ground up, while others are forks that have taken over development. Send falls in the latter category, and remains one of my top choices for sharing large files.

https://timvisee.com/projects/ffsend

== Password Manager

=== KeePassXC

I prefer storing my passwords and other sensitive information offline, and handle the synchronization between devices using a dedicated program like Syncthing.

https://keepassxc.org
