= Asciidoc Over Markdown
D10f <devontheroof@pm.me>
v1, 2024-06-11
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:description: The better way of taking notes for structured content
:keywords: asciidoc, markdown, notes, productivity
:technologies: asciidoc markdown nextjs
:source-highlighter: pygments
:icons: font
:toc:

Preamble about note taking.

== Advantages Of Plain Text

A while ago, I watched a fantastic video about the many benefits of plain text over other formats, titled https://www.youtube.com/watch?v=WgV6M1LyfNY[The Unreasonably Effectiveness Of Plaintext]. It's a really good watch (the rest of channel is also pretty good) and I'm inclined to agree with most, if not all, of what is said about plain text.

//...Talk about advantages of plain text over other formats / summarize the video's bullet points.

== What Is Markdown

Markdown is a hugely popular format used to write plain text in such a way that it can be easily parsed both by humans and machines. Using dedicated software, it's very easy to create a nicely presented document that preserves the benefits of plain text discussed above.

One of the main advantages of markdown is that's very simple. It's very easy to get started with, remember the syntax and finding examples online. The simplicity, in turn, drives up adoption and with that a healthy ecosystem of clients to read and write in various flavors of Markdown. Discord uses it, as well as Discourse, two very popular web-based software used by millions.

There is one small problem, however: it's not a _standard_. Being as simple as it is has some downsides as well, and people have come to expect more features to be integrated. But it's up to each client to choose what and how to implement them, if at all. It becomes impossible to guarantee consistency when different client applications support different syntax and features, and render documents in different ways.

At the time of this writing, https://github.com/style-guides/Markdown[GitHub's markdown flavor] is the most popular (to my knowledge anyway).

== What Is Asciidoc

Asciidoc is also a format used to write plain text documents, often rendering them other standard formats such as PDF. There are two big differences with markdown: there is a https://docs.asciidoctor.org/asciidoc/latest/[documented syntax], and has a lot more features.

NOTE: Fun fact: all my blog posts are written in plain text, using Asciidoc.

The primary tool used to generate output is `asciidoctor`; it can convert files to HTML or PDF formats. Additional libraries and bindings exist for programming languages, like https://docs.asciidoctor.org/asciidoctor.js/latest/[asciidoctor.js].
