= Effective Password Management
D10f <devontheroof@pm.me>
v1, 2024-11-27
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:description: Manage your passwords effectively; hacker- and future-proof.
:keywords: linux password keepass keepassxc
:technologies: shell keepassxc
:source-highlighter: pygments
:icons: font
:toc:

Passwords are one of many ways to confirm that we are who we say we are. By knowing a secret that no one else could possibly know, we are confirming our identity with a strong degree of certainty. It's a simple yet effective method, but only as long as the password remains secret: if someone else is able to guess or deduce it through social engineering, the magic is gone.

The obvious solution is to use a password that is hard to guess. Unfortunately, humans are notoriously bad at remembering long passwords. So, what is the best way to create such a strong password while still being able to use whenever we need to?

== Using A Password Manager

A password manager is software that can generate perfectly random strings of characters, and keep track of them. Whenever you need to enter your password you can look it up inside your password manager.

This doesn't sound too different from storing your passwords in a plain text file or a post-it note glued to your desk. But password managers offer two important features: they can fill forms automatically for you, so you don't even have to know what your password is, and they typically store data in an encrypted form.

=== Pros

1. Strong passwords.
2. Different password for every account.
3. No need to remember dozens of them.

=== Cons

1. Inconvenient to use on other computers. You would have to install the same software or browser extensions, which may not even be possible on restricted environments.
2. All passwords in one basket, so to speak. Losing access could prove catastrophic as you would lose access to important accounts. It would be even worse if this fell into the wrong hands.

== Double Blind Password Method

Recently I discovered a video that talks about a "double-blind" password strategy for keeping passwords secure. It essentially combines the usefulness of a password manager to, well, manage your passwords securely, and a unique secret that only you know.

The advantage is that your actual password is never exposed to the service that you've signed up for, even if there were internal malicious actors or an attacker managed to walk away with a database full of user data.

It's a simple method, yet effective. However, there are a couple of caveats to this approach that can be improved by using the password manager features _effectively_.

=== Auto-Type Actions

The issue is that it requires user interaction while entering the password. Considering that most passwords have the ability to auto-complete the login form fields, this seems a bit of a step back. So, how to avoid this?

First, let's see how to replicate the exact same behavior as shown in the video by using KeePassXC's Auto-Type placeholders.

1. Create a new entry with a username and password.
2. In the Auto-Type section for that entry, select "Use custom Auto-Type sequence".
3. Append the default sequence with `{PICKCHARS}`.

Save the changes and try to use the auto-type feature for that entry. A popup window will appear to prompt you to type a few characters in the text box, or select a few numbers.

Reference to video https://www.youtube.com/watch?v=boj9q26gadE

== KeePassXC Auto-Type Feature

Let's discuss the powerful auto-type capabilities of KeePassXC. In its simplest form, it does exactly what it sounds like: types the username and password for you automatically. More specifically, it uses a default typing sequence of `{USERNAME}{TAB}{PASSWORD}{ENTER}`, where the `USERNAME` and `PASSWORD` are the respective fields for that entry. +
Some sites use fancy multistep forms that require you to adjust this sequence to something like this: `{USERNAME}{TAB}{ENTER}{DELAY 1000}{PASSWORD}{ENTER}`. This enters the username first, waits for a second &mdash; usually enough for the service to reply that it's a valid username &mdash; and then proceeds with the password.

This is very convenient as all you have to do is trigger the auto-typing somehow, but the hidden superpower of this feature are the various placeholders that exists and that you can combine however you want to create your own custom sequence. Let's implement this same double-blind mechanism from the video above using only KeePassXC's.

. Create a new entry for a service.
. Fill in the username and generate a random password.
. For the secret, the double-blind, pick any numbers between 1 and the password length. For example, for a password of 20 characters you can pick: 3, 17, 15, 19, 1.
. Create a custom auto-type sequence using the following placeholders: `{USERNAME}{TAB}{PASSWORD}{PICKCHARS}{ENTER}`.

What `PICKCHARS` does is bring up a popup for you to type any numbers that you want between 1 and the character length. It will then refer back to the password field and add those characters to the end of the password. This is where you can type the double-blind secret.

Check out https://keepassxc.org/docs/KeePassXC_UserGuide#_auto_type[KeePassXC documentation] to know more about how to set up all this.


