= Convert Videos To Animated Images
D10f <devontheroof@pm.me>
v1, 2025-09-05
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:description: 
:keywords: linux cli imagemagick ffmpeg gif
:technologies: shell ffmpeg
:source-highlighter: pygments
:icons: font
:toc:

A video and an animated image aren't all that different. The illusion of movement is achieved by playing a sequence of images in succession, quickly enough to trick the brain into thinking that the picture is moving.

However, I don't usually need the same level of detail in animated images as I do in videos. Depending on the use case, it's possible top get away with fewer frames and higher compression rates, in order to produce smaller files that can be shared easily online or as email attachments.

This also plays nicely into the strengths of art styles like Lo-Fi, pixel art, retro, etc.

It's all about choosing the right [.line-through]+tool+ format for the job, and knowing how to convert between one and the other is very useful.

== Choosing The Right Format

There are three main formats that I like to use when working with animated images: GIF, WebP and AVIF. Which one to use depends on type of content that I'm working with, the desired file size, the original file size, how much patience I have to wait around for the codecs to process the whole thing, etc.

I talk a little bit more about xref:_loading_images_efficiently[relatively new image formats] in another post.

=== To GIF

The trusty GIF format has been around for a long time now. Unfortunately, there are still many platforms that only accept this format, being as popular as it is. 

It's quite fast to process but has the worst quality/size ratio. To convert a video use the command:

[source,console]
----
$ ffmpeg -i input.mp4 \
    -vf "split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" \
    -loop 0 \
    output.gif
----

This bit right here is of special interest: `split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse`. Why is this important is whole other topic, but essentially GIF files are limited to 256 colors. Providing an accurate color palette taken from the video frames will improve the quality of the final image.

So, this video filter splits the video into two streams, referenced by the variables `s0` and `s1`. The first stream is passed to the `palettegen` function, which stores its result in the variable `p`. The second stream is then provided to the `paletteuse` function, along with the that was just generated.

It's possible to generate the palette in a separate step and save that to a file, in case you need to reuse it for other animated images:

[source,console]
----
$ ffmpeg -i input.mp4 -vf "fps=10,scale=320:-1:flags=lanczos,palettegen" palette.png # <1>
$ ffmpeg -i input.mp4 -i palette.png -lavfi "[s0]; [s0][1:v] paletteuse" -loop 0 output.gif # <2>
----
<1> Generate the color palette and save it to a file.
<2> Use the palette in creating the animated GIF.

Make sure the filter settings (fps, scale, etc) are the same on both commands.

=== To WebP

WebP is much simpler to work with, since we can provide familiar properties to control the quality and compression settings easily. This format has a good balance between speed, quality and file size.

[source,console]
----
$ ffmpeg -i input.mp4 -loop 0 -quality 50 -compression_level 6 <output>.webp
----

=== To AVIF

For AVIF, we can do:

[source,console]
----
$ ffmpeg -i input.mp4 -loop 0 -crf 60 <output>.avif
----

real    17m17.003s
user    27m46.480s
sys     0m1.725s

TIP: You can read all about each codec's options from the https://ffmpeg.org/ffmpeg-codecs.html[ffmpeg documentation page]. For AVIF

== Practical Example

Let's look at a practical example to see the difference between each file format. I have a 15 second, 4K resolution video file saved in MP4 format and of about 82 MB in size. I want to convert that in order to upload it to a website very much like this one, but could be anywhere in the web.

To keep things at an acceptable size we'll scale down the output to 720px (HD), and play the animation at 24 frames per second. To do that, we can use the video filter option like so `-vf "fps=24,scale=-1:720:flags=lanczos"`.

And these are some benchmarks after running various commands with different settings for each file format:

.Video to animated image file benchmarks
[%autowidth%header]
|===
| | GIF                | WebP | AVIF |

// First column
| Time |

real    0m5.418s +
user    0m31.304s +
sys     0m0.306s |

real    17m24.686s +
user    28m6.698s +
sys     0m1.609s |

real    17m24.686s +
user    28m6.698s +
sys     0m1.609s |

// Second row
| File size | 3.7M | 690K | 313K |

|===

== Extracting Frames Into Multiple Images

...

