= Different Types Of Identifiers
D10f <devontheroof@pm.me>
v1, 2024-06-21
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:description: Talks about different ways of identifying unique resources and their pros and cons.
:keywords: id uuid cuid snowflake
:technologies: shell
:source-highlighter: pygments
:icons: font
:toc:

An _id_ is, by definition, unique. However, there are different ways to generate identifiers. It's a seemingly trivial problem but using the wrong way of identifying resources can lead to big problems, particularly when working with large amounts of data.

== Sequential Id

One very straight forward way to assign a unique value to each record is to keep a counter variable that increase over time. Since there are infinite numbers, this simple method guarantees uniqueness for as long as the counter variable can be referenced. This method is very efficient for things like sorting based on the ID, but introduces a piece of state that needs to be managed carefully in distributed systems.

SQL databases use an auto-increment function for each new record inserted into a table. Note that each table keeps track of its own records so it's possible for different tables to share the same id. In this sense, this method guarantees uniqueness only when combined with a namespace i.e., the table name.

[source,typescript]
----
class ComponentFactory {
    static componentTypeCounter: number;
    static componentIdMap: Map<ComponentType, number>;

    constructor() {
        ComponentFactory.componentTypeCounter = 0;
        ComponentFactory.componentIdMap = new Map();
    }

    create<T extends ComponentType>(componentType: T, args: ComponentArgs<T>) {
        return new BaseComponent(
            this.calculateId(componentType),
            componentType,
            args
        );
    }

    private calculateId(componentType: ComponentType) {
        let id = ComponentFactory.componentIdMap.get(componentType);
        if (id === undefined) {
            id = ComponentFactory.componentTypeCounter;
            ComponentFactory.componentIdMap.set(
                componentType,
                ComponentFactory.componentTypeCounter++,
            );
        }
        return id;
    }
}
----

== UUID

+ Universal Unique Identifiers
+ 128-bit (16-bytes) block of data

In JavaScript, the Crypto API implements a convenient method to generate random UUIDs that works exactly the same in browser environments as it does within the Node.js runtime.

[source,javascript]
----
crypto.randomUUID();
----

[literal]
Output:
37987521-8da8-4a13-af38-76e194478775

=== Time/MAC

=== Name IDs

=== Randomly Generated

== GUID

== ULID

+ Universally Unique Lexicographically Sortable Identifiers
+ 128-bit (16-bytes block of data)

https://yt.drgnz.club/watch?v=hGBHGficAiM[Generate Unique Identifiers In Your Programs]
https://yt.drgnz.club/watch?v=2MbFDR7qt5U
https://yt.drgnz.club/watch?v=zIebRwU0FOw


