= Setup And Configure A Wireless Access Point
D10f <devontheroof@pm.me>
v1, 2024-10-24
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:description:
:keywords: linux debian firewall network wireless networkmanager
:technologies: shell linux
:source-highlighter: pygments
:icons: font
:toc:

Setting up a wireless hotspot through an external interface, like a USB pluggable antenna, can be an easy and convenient way to share internet access with other devices. It can be tricky to set up, however, while simultaneously running a firewall.

This post aims to clarify the _hidden_ gotchas to work around, and to provide concise instructions using the command line as well as graphical interface.

== Display Network Interfaces

First things first, make sure that the external wireless interface is detected properly by the system.

[source,console]
----
$ nmcli device
----

[literal]
DEVICE             TYPE      STATE                   CONNECTION
enp1s0             ethernet  unavailable             --
wlp0s20f3          wifi      connected               roof
wlxc8d3a30499bc    wifi      disconnected            --
lo                 loopback  connected (externally)  lo
docker0            bridge    connected (externally)  docker0
virbr0             bridge    connected (externally)  virbr0

In this case, the USB antenna that I've plugged in appears as `wlxc8d3a30499bc`. Good, now we need to create a new connection for it.

== Create A New Connection

For this we'll use Network Manager, as it's probably already running in your system. The first thing to do is to register a new connection, which in NM's lingo means a new configuration file that defines things like the name of the connection, security level, etc.

IMPORTANT: Note that this does not mean an actual connection will be made, it just makes one available for network interfaces to bind to. Setting this manually can be useful for example to connect to hidden wireless networks.

To create a simple access point, the `nmcli connection add` command will do the trick nicely, although it can be intimidating given the number options available to use, some of which are not very self-explanatory.

[source,console]
----
$ nmcli connection add \
    type wifi \
    ifname wlp01 \ # <1>
    con-name MyHotspot \ # <2>
    ssid HelloThere \ # <3>
    autoconnect yes \
    wifi.hidden false \ # <4>
    802-11-wireless.mode a \ # <5>
    802-11-wireless.band bg \ # <6>
    802-11-wireless.security wpa-psk \ # <7>
    wifi-sec.psk secret1234! \
    ipv4.method shared
----
<1> Name of the interface to bind to this connection.
<2> Name of this connection profile, used internally by Network Manager.
<3> Visible name of the WiFi connection.
<4> Hidden connections don't provide much security, and can be inconvenient to have them hidden. Defaults to true.
<5> ...
<6> ...
<7> Specifies the security mechanism for the connection. A setting of "wpa-psk" means that is password protected.

This command will create a new configuration file in `/etc/NetworkManager/system-connections/<con-name>.nmconnection`. This file can be safely be edited manually, although it requires reloading the Network Manager for changes to take effect. Another way of editing an existing profile is to use the `nmcli connection modify` command.

Manage connections using `nmcli connection {up,down} <connection_name>`.

== Configuring The Firewall

If there is a firewall running, it may block incoming traffic to the network interface, making the connection to the access point impossible. There are a few ports that need to be allowed in order for this to work properly, and in the interest of preserving the principle of least privilege, we want to add those firewall rules only to the appropriate interface.

=== Using UFW

Using the Uncomplicated Firewall, default firewall software used by Ubuntu, the rules can be added using the commands:

[source,console]
----
$ sudo ufw allow in on <interface_name> to any proto udp port 53,67,68
$ sudo ufw allow in on <interface_name> to any proto tcp port 53
----

Note that the interface name may not be specified as an alias, which is not supported by UFW.

== Prerequisites (OLD)

In this post I'll be covering how to set up firewall rules using two of the most popular firewall packages that exist on Linux: `UFW` and `firewalld`.

WARNING: Note that is not recommended to have more than one firewall active and running at once, as they will interfere with each other.

For the purposes of this post, the scenario would be a simple setup of a laptop using an external USB Wi-Fi adapter to provide internet to an Android smartphone.

=== Installing UFW

The Uncomplicated Firewall is the default firewall configuration tool for Ubuntu, and is likely already installed in your system. If that is not the case, you can install it separately by running a simple command:

[source,console]
----
$ sudo apt install ufw
----

There is also a very nice (and completely optional) graphical interface that can be used alongside of it, called `gufw`. I'll be using both in this post for completeness' sake.

== Issue: Unable To Connect To The WiFi Access Point

To allow the connection between an external device trying to connect to the hotspot, we need to allow some traffic to the network card providing the hotspot. Granting unrestricted access to the network card is an unnecessary security risk; we want to follow the principle of least privilege and only create the least amount of exceptions as we can get away with. To that effect, the rules that we need are:

DNS :: Domain Name Service in order to resolve addresses
