= Generic Data Structures In C
D10f <devontheroof@pm.me>
v2, 2025-05-02
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:description: An approach to writing generic data structures in the C programming language.
:keywords: c programming data_structures generics
:technologies: c
:source-highlighter: pygments
:icons: font
:toc:

While there are a myriad of online articles and books written about this topic, this is one of the milestones that I've been meaning to conquer when it comes to understanding memory management. In this post I'm covering a single data structure that exists in just about every other language and is one of the most widely used: the dynamic array.

== Generic Types

Unlike other programming languages, C does not have generic types. This makes the task of creating flexible and easily reusable data types much more difficult, and verbose, in comparison to those languages.

One of the few mechanisms to achieve that same behavior are __void pointers__, which are tedious to use and can be quite dangerous sometimes.

== Arrays & Dynamic Memory

An array is a collection of items arranged sequentially one after another. In terms of programming, an array is a space of memory reserved to store a certain number of elements of a certain type. By knowing the type, we also know the amount of memory each item takes, and we ask the operating system to set aside exactly that many bytes of memory for us.

Over time, the array fills up and we need to request more memory, then relocate the items in the existing array over to that new one. Many other programming languages keep track of all of this automatically, and wrap it as a nice data structure that is ready to use; in C++ these are known as vectors, and ArrayList in Java.

Like so many other things, this has to be handled explicitly in C &mdash; act surprised.

== The Problem

Many other articles that I've found on the topic talk about creating this data structure, a dynamic array that resizes automatically and that stores items of any type. However, I was surprised to see how many of them miss the mark completely by creating an array that stores void pointers, instead. This does solve the first problem of having a generic data structure, but the actual items that the array is supposed to be holding are scattered through the memory. This incurs an additional penalty when iterating over the array, and can undermine the CPU's cache mechanism by creating a lot of cache misses, slowing things down further.

I don't want sound too critical about this. There are very valid reasons to use this approach instead of the one that I'm proposing. For example, it wouldn't be wise to copy large chunks of memory if they are already stored elsewhere, especially if memory is limited or memory fragmentation is a real concern. +
As usual, it's all about the context. This post is about data structures and memory management in C, and I'm using this particular example to explore the topic a bit in depth.

== +++<s>The</s>+++ A possible solution

In short, once the array is created, and we're ready to add items to it, we want to copy them entirely to the memory.
