= Seven Languages In Seven Weeks
D10f <devontheroof@pm.me>
v1, 2025-11-10
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:description: Just as each new spoken language can make you smarter and increase your options, each programming language increases your mental tool kit, adding new abstractions you can throw at each new problem. Knowledge is power. The Seven in Seven series builds on that power across many different dimensions.
:keywords: programming oop object-oriented-progamming functional-programming
:technologies: ruby lua prolog scala erlang clojure elixir
:source-highlighter: pygments
:icons: font
:toc:

I've recently come across the book https://pragprog.com/titles/btlang/seven-languages-in-seven-weeks/[Seven Languages In Seven Weeks], by Bruce A. Tate. Before even starting to read it I was already pretty excited about it. It felt like a nice way out of my routinely used programming paradigms using the same languages over and over. And while that's useful and also interesting, it just felt like a nice change of pace.

However, as I noticed a second part to this book with seven more languages, I decided to mesh them together to pick the ones that I found most interesting to learn. And so, the final list of looks like this:

1. Ruby
2. [.line-through]#Io# Lua
3. Prolog
4. Scala
5. Erlang
6. Clojure
7. [.line-through]#Haskell# Elixir

As these things tend to go, I doubt that I will be able to keep up the pace of one week per language, but I'll give it a try and aim to at least be consistent and finish the book.

== Ruby

include::../includes/seven_in_seven/ruby/post.adoc[tags=!title]

== Lua

include::../includes/seven_in_seven/lua/post.adoc[tags=!title]

== Comparison Exercises

One way of comparing these programming languages is by working through a small set of exercises. While not every programming language is designed to solve the same type of problem, this is a good baseline for such a short period of time to learn each of them. Plus, it's also an excuse to put the concepts learned into practice.

I'm pretty much coming up with this list of exercises as I go, trying to pick those that I find interesting and that are the "fairest" to compare on this list of programming languages.

Roman numeral converter :: ...

Wordle :: ...

Maze generator :: Implementation of a simple maze generator algorithm (yet to be determined), extracted from Jamis Buck's "Mazes For Programmers" book. The examples are written in Ruby, so I'm cheating a little bit with the first language already, but I think it's a good exercise nonetheless.

File duplicate detector :: Hashing, file handling

Sudoku Solver :: Recursion

Picture Of The Day :: Networking

Balanced Binary Tree Checker:: Data structures and algorithms

Circular Ring Buffer Log :: Data structures and algorithms

Port Scanner Enumeration :: Networking, cybersecurity

Rotten Apples :: https://www.codechef.com/practice/course/matrices/MATRICES/problems/MATROTAPPLE

