= Writing A Simple HTTP Client
D10f <devontheroof@pm.me>
v0.1, 2025-07-17
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:description: working with low-level sockets to create an http client
:keywords: sockets networking http https ssl python
:technologies: python
:source-highlighter: pygments
:icons: font
:toc:

The beauty of making things from scratch is you get to understand how everything works. And sometimes, that is the best decision to make depending on your needs, for example when there are particularly tricky requirements, or when you need to avoid any dependencies to make the script easy to use.

After dabbling a little bit with https://codecrafters.io[Code Crafters] I decided to attempt to write my own implementation of a simple HTTP client. I don't need anything fancy, just that it can make simple requests to a remote server and handle a few status codes. More than enough to update one of my Python scripts to make it a little bit faster, and more portable as well, by removing all dependencies.

Throughout this whole seemingly trivial exercise there are actually a lot of concepts to pay attention to. Things like string formatting, dates and time, network sockets, HTTP standards, and more.

== The Socket Network Interface

One of the design goals of sockets is to enable two processes running on separate machines to talk to each other. There are different types of sockets, but our HTTP client will use the TCP/IP protocol, as that's the _de facto_ standard to communicate over the internet.

=== Socket File Descriptors

Like so many other things in the UNIX world, everything starts with a file.

A socket is represented by a file that can be written to and read from, effectively enabling communication between two ends. Different types of sockets exist, but in all cases they are handled as file descriptors with properties specific to sockets.

In Python we use the `socket` module to create a socket:

[source,python]
----
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
----

This function works much like reading any other file. It returns a file descriptor that we must close when we're done working with it by invoking the appropriate method:

[source,python]
----
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.close() # [!code ++]
----

The constructor function accepts at least two parameters that define the socket _domain_ and _type_. In this case, `AF_INET` means "IPv4 Internet Domain" and `SOCK_STREAM` means "TCP". Since TCP is a connection-based protocol, we need to establish a connection to the remote server before we can send anything over the wire:
