= Install Linux Over The Network
D10f <devontheroof@pm.me>
v1, 2024-06-11
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:description: Install Linux without any external media device, over the network, using the PXE system.
:keywords: linux network pxe tftp
:technologies: shell
:source-highlighter: pygments
:icons: font
:toc:

Some preamble / introduction

== Problem Statement

You need to install an operating system on your computer (the client), but you don't have any external media device available to install from (maybe because the physical ports are damaged).

On the same network you have another computer (the server) with the ISO file for the operating system you want to install. You want to use this computer to act as a server, using the ISO file stored there to boot over the local network.

You will need to install software on this machine to turn it into a server capable of listening for network requests to set up the connection between it, and the client.

IMPORTANT: There are multiple ways to set this up. This post attempts to provide a straight forward, practical approach following a step-by-step instruction. Please keep this in mind when comparing and contrasting the information you see here with other sources.

== Definitions

These are the parts involved in this process. They are defined in the context of Pre-Execution Environment (PXE), booting a computer over the network.

=== DHCP Server

The Dynamic Host Configuration Protocol is used to assign communication parameters to each host on a network, most commonly an IP address for identification purposes. In this case however, we're interested in other parameters that will help with the net-boot process, by means of directing the client machine to the location of the TFTP server.

=== TFTP Server

The Trivial File Transfer Protocol is used for transferring files over the network, commonly used in the early stages of the boot process due to its simplicity compared to more sophisticated alternatives. It will be used to serve the client with the bootloader and other files as needed.

=== Network Bootloader

A bootloader is the software that runs before the operating system. It's responsible from loading and transferring control over to the _kernel_ i.e., Linux, which in turn loads the operating system itself. +
Since we want to boot over the network we need a PXE bootloader that will be served from the TFTP server.

=== GRUB

GNU GRUB is another bootloader specifically made for personal computers. Most Linux distributions today use it as a mean to select the operating system to boot into (even when there is only one). We will use this once all files have been downloaded over the network and our system is ready to boot into the remote ISO image, which will be downloaded separately over HTTP.

=== HTTP Server

Once the client has received the bootloader files, has loaded the GRUB menu and selected an option to choose from (for simplicity, in this example there will be only one option), the ISO image needs to be downloaded by the client. We'll use a basic but reliable server to that effect, using the well-known HTTP protocol.

=== ISO File

The target image that we want to boot into. For example, we'll go with Linux Mint 21.3 "Virginia".

== Setup

IMPORTANT: The following commands need to be run as root.

We need to install a few packages and configure them. There are only a handful of them, so we can do it in one go:

[source,console]
----
# apt install dnsmasq pxelinux syslinux
----

=== dnsmasq

Despite the name, `dnsmasq` does a lot more than providing DNS and, in fact, we are not interested in these capabilities for the purposes of this post. It's the DHCP _with proxy capabilities_ and the TFTP server that we need for this to work.

[source,title="/etc/dnsmasq.conf"]
----
port=0 # <1>
enable-tftp # <2>
tftp-root=/srv/tftp # <3>
tftp-port-range=7000,7100 # <4>
dhcp-range=192.168.1.0,proxy # <5>
pxe-service=x86PC,"PXELINUX (BIOS)",bios/pxelinux # <6>
pxe-service=x86-64_EFI,"PXELINUX (EFI)",efi64/syslinux.efi # <7>
log-queries # <8>
log-facility=/var/log/dnsmasq.log
----
<1> Disables the DNS server.
<2> Enables the TFTP server.
<3> The directory where the TFTP server will be hosting the files to boot from.
<4> After the initial connection to the TFTP server, a random port will be selected automatically for all subsequent exchanges. Specifying a range of ports here will narrow down the number of ports to be used, making it easier to create predictable firewall traffic rules.
<5> Specifies the local network to listen to for DHCP requests (make sure to update this to match your network). The "proxy" mode instructs dnsmasq to only provide PXE information to clients while another DHCP server handles the IP assignment.
<6> Bootloader to use for BIOS powered devices.
<7> Bootloader to use for UEFI powered devices.
<8> Useful for debugging and seeing the traffic generated.

We need to create the directory for the TFTP server to host the files, as per the configuration above. In addition, we need two separate directories to contain the files required by BIOS- and UEFI-powered systems, respectively:

[source,console]
----
# mkdir -p /srv/tftp/{bios,efi64}
----

And restart the service:

[source,console]
----
# systemctl restart dnsmasq.service
----

=== Bootloader Files

The _bootloader_ will be among the files served by the TFTP server. All we need to do is place these files (which we obtained when we installed the packages to that effect earlier) at the root of the TFTP server, as per our previous step.

[source,console]
----
# cp /usr/lib/syslinux/modules/bios/{ldlinux,vesamenu,libcom32,libutil}.c32 /usr/lib/PXELINUX/pxelinux.0 /srv/tftp/bios
# cp /usr/lib/syslinux/modules/efi64/ldlinux.e64 /usr/lib/syslinux/modules/efi64/{vesamenu,libcom32,libutil}.c32 /usr/lib/SYSLINUX.EFI/efi64/syslinux.efi /srv/tftp/efi64
----

IMPORTANT: Having both bootloader types will be beneficial if you are not sure which one you'll need.

=== Create GRUB menu options

Next up, we need to define entries for the GRUB menu. This will allow us to choose the files we want to use to boot our computer (as per the previous step). Create a directory called `pxelinux.cfg` with a single file, `default`. This file will have a very bare menu with a single option for the ISO that we want to boot into:

[source,title="/srv/tftp/pxelinux.cfg/default"]
----
UI     vesamenu.c32

LABEL Mint Cinnamon 21.3 network boot
	MENU LABEL MINT CINNAMON 21.3
	KERNEL ::boot/casper/vmlinuz
	INITRD ::boot/casper/initrd.lz4
	APPEND root=/dev/ram0 ramdisk_size=1048576 ip=dhcp netboot=url url=192.168.1.10/linuxmint-21.3-cinnamon-64bit.iso # <1>
----
<1> Make sure to update the IP address to point to the server.

The `KERNEL` and `INITRD` lines define the files served by the TFTP server, that are used to boot over the network. The `::` serves as a placeholder for the root directory as defined in `dnsmasq.conf`. This means that we need to have a `boot` directory containing this temporary bootloader and kernel files, which we'll create next.

The `APPEND` line defines additional parameters for the kernel. Here we specify how to boot and where to load the actual live ISO file. Make sure the IP address points to the right server. It may work with domain names as well, but I haven't tried it.

In order to use this file regardless of whether the client machine runs on BIOS or UEFI, we can create symbolic links to it in either of the respective folders we created earlier.

[source,console]
----
# ln -s /srv/tftp/pxelinux.cfg /srv/tftp/bios/pxelinux.cfg
# ln -s /srv/tftp/pxelinux.cfg /srv/tftp/efi64/pxelinux.cfg
----

== Extract ISO file

Finally, we need the ISO image itself to serve it to the client machine. Specifically we need to extract the files from the image and copy them to the root of the TFTP server. We can do this in two steps by mounting the image files in a temporary location:

[source,console]
----
# mkdir /mnt/linux_mint
# mount -o loop -t iso9660 ~/Downloads/linuxmint-21.3-cinnamon-64bit.iso /mnt/linux_mint
----

And then copying them over to the TFTP server's root directory:

[source,console]
----
# mkdir /srv/tftp/boot
# cp -r /mnt/linux_mint/* /srv/tftp/boot/
----

At this point, we should have a file structure that looks something like this:

[literal]
/srv/tftp/
├── bios/
│   ├── ldlinux.c32
│   ├── libcom32.c32
│   ├── libutil.c32
│   ├── pxelinux.0
│   ├── pxelinux.cfg -> /srv/tftp/pxelinux.cfg
│   └── vesamenu.c32
├── boot/
│   ├── boot
│   ├── casper
│   ├── dists
│   ├── efi
│   ├── isolinux
│   ├── md5sum.txt
│   ├── pool
│   └── README.diskdefines
├── efi64/
│   ├── ldlinux.e64
│   ├── libcom32.c32
│   ├── libutil.c32
│   ├── pxelinux.cfg -> /srv/tftp/pxelinux.cfg
│   ├── syslinux.efi
│   └── vesamenu.c32
└── pxelinux.cfg/
    └── default

WARNING: The boot/ directory might look slightly different depending on the ISO image used.

== Firewall Rules

As PXE involved accessing files over the network it's possible that a Firewall blocks some of the connections. We can create the following rules in order to work around that:

[source,console]
----
# ufw allow 67/udp # <1>
# ufw allow 69/udp # <2>
# ufw allow 7000:7100/udp # <3>
# ufw allow 4011/udp # <4>
# ufw allow 80/tcp # <5>
----
<1> DHCP traffic.
<2> Initial connection to the TFTP server.
<3> Subsequent connections to the TFTP server. This range should match whatever was provided in the dnsmasq configuration file.
<4> PXE server.
<5> HTTP traffic to download the ISO file.

== Run The HTTP Server

We don't need anything special for this, so we can use Python's HTTP module as it comes built-in and Python is likely installed in most Linux distributions by default.

[source,console]
----
# python3 -m http.server 80 -d ~/Downloads
----

The location does not matter; point the `-d` or `--directory` option to wherever directory in your server machine the ISO file is located. Note that we're not referring to the extracted files anymore but the image itself.

== Start The Client

IMPORTANT: Wi-Fi does not typically work in the early steps of the boot process. You will need to use an Ethernet connection for the client machine to reach the network.

With all this in place we can now start the client machine. It might take a while, but it should automatically start downloading the bootloader files, and then you'll be presented with the GRUB menu, in this case with a single entry to boot into Linux Mint. Then, it will download the ISO file and finally start the operating system.
