= Finding Files In Linux
D10f <devontheroof@pm.me>
v2, 2021-05-05
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:description: There are multiple ways to search for files in Linux: by name, size, permissions... as with most things there are pros and cons to all them.
:keywords: linux, unix, find, locate, shell, bash
:technologies: shell
:source-highlighter: pygments
:icons: font
:toc:

Finding something can be straight forward, or immensely complicated. It all depends on what you are looking for, what criteria and how much time you have available. Learn the tools of the trade to get the job done.

== Find

The most obvious tool for the job is `find`. It's quite straight simple to use: specify the directory to look in and the criteria to search by:

[source, console]
----
$ find [directory] [options] [expression]
----

Below the apparently simplicity hides a myriad of options that makes it one of the most valuable tools under a system administrator's tool belt. Although it's not without some hidden gotchas that will make you reach for the manual once or twice (especially if it's been a while since you've used it).

=== By Name

[source, console]
----
$ find /etc -name deluser.conf
$ find /etc -iname deluser.conf
$ find /etc -iname *user.conf
----

The `-name` and `-iname` options allow specifying the name of the file you're looking for. Since an exact match is required, using glob patterns can be really convenient to find multiple files that follow a similar structure. You can also use `-regex` and `-iregex` instead, to take advantage of full regular expressions in your query.

// [source, console]
// ----
// $ # Example i 
// ----

=== By Size

The `-size` option can be used to search for files of a given size. It accepts an argument *n* that represents the size of the file to search for, and optionally a prefix of or suffix to further narrow down the search criteria.

[source, console]
----
$ find ~/Downloads -size +1G # <1>
$ find ~/Downloads -size -1M # <2>
$ find ~/Downloads -size 64k # <3>
----
<1> Matches files greater than 1 Gibibyte.
<2> Matches files smaller than 1 Mebibyte.
<3> Matches files of exactly 64 Kibibytes.

=== By Time

This is a powerful option to know about but can get tricky to remember, and I keep going back to the manual pages to refresh my memory on how to use it properly. It searches for files based on the time they were created, last modified.

[source, console]
----
$ find $HOME -cmin -2 # <1>
$ find $HOME -mtime 0 # <2>
$ find $HOME -atime +2 # <3>
$ find $HOME -anewer /var/log/auth.log # <4>
----
<1> Matches files that were modified less than 2 minutes ago.
<2> Matches files whose _contents_ were modified within the last 24 hours.
<3> Matches files that were accessed over 48 hours ago.
<4> Matches files that were accessed more recently than the `/var/log/auth.log` file.

Each option is prefixed by _a_, for access, _c_ for status change or _m_ for modified. Then, _min_ refers to minutes whereas _time_ refers to 24 hours periods. Lastly, the _newer_ option compares each file against the time attributes of a given one.

=== By Date

It's also possible to search for files on a specific date, although with a little fiddling of the inner workings of `find`. Let's jump right into it:

[source,console]
----
$ find $HOME -newermt 2021-05-05 # <1>
$ find $HOME -newermt $(date +%F) # <2>
$ find $HOME -newermt "Two days ago" # <3>
----
<1> Matches files that were modified on the specified date.
<2> The date used for reference as used by the `date` command.
<3> Relative strings can also be used!

As you can see, we can specify exact or relative dates using different formats. Checkout the https://www.gnu.org/software/coreutils[documentation page] to see the full capabilities and limitations. Here, the _mt_ stands for modified time; similarly _ct_ exist for created and _at_ for accessed times.

To specify a range use:

[source,console]
----
$ find $HOME -newermt 2021-05-01 ! -newermt 2021-06-01
----

The first expression searches for files modified after the first of May 2021. The second expression is preceded by the negation operator, and specifies newer than June 2021, thereby creating a range for the whole month of May.

=== By File Attributes

There are many file attributes that can be used to search for files. Some of the common attributes that I find myself (ha!) using regularly are `-perm` for permissions, `-type` for file type, and `-uid` and `-gid` for user and group IDs.

There are some other modifiers like `-not` that allow to perform more interesting pattern searching. When considering security it may be more productive to search for things that are out of place, for example.

[source, console]
----
$ find /var/www/html -type f -not -perm 640 # <1>
$ find /var/www/html -type d -not -uid 33 # <2>
$ find /var/www/html -type l # <3>
----
<1> Matches files that don't have a specific set of permissions.
<2> Matches directories not owned by the user with ID of 33 (typically `www-data` in web servers).
<3> Matches only symbolic links (can be used to identify broken configurations with Nginx).

== BFS

This is an interesting one that can be quite handy to know about. To all intents and purposes it's identical to `find` in how it's used and what it does, but differs in _how_ it does it. Whereas `find` uses a _depth-first search_ algorithm, `bfs` uses a _breath-first search_ one, hence the name.

In summary, both of these utility tools will _eventually_ find the file(s) in question. It's a matter of how choosing the better tool depending on what you are looking for, and whether you have some idea of where that might be found.

Checkout the https://github.com/tavianator/bfs[project's repository] to learn more about how to install it and what other options are available.

== Locate

The `locate` command does not search for files directly, it searches an index that is created by the command `updatedb` which automatically runs once a day. This in turn means that results are usually very fast with the downside that the index may not be entirely up-to-date. While this is updated automatically for you, you can still run `sudo updatedb` manually.

The results are based on a match on the file name, and it returns them as a list by their absolute path. It won't however return any matches within directories without read permissions such as `/etc` or `/bin`.

== GREP

This powerful utility is designed to match character patterns a text input. It can be useful when we are looking for a file that contains a particular word or pattern, among many other use cases. +
At its most basic form, you provide a pattern followed by the file(s) that you want to search through:

[source,console]
----
$ grep ...
----

You can also provide it with a path and let it scan all the contents recursively, by passing the `-r` or `--recursive` flag (there is also the `-R` flag to follow symbolic links).

[source,console]
----
$ grep "" -r .
----

If you want to avoid searching some locations, use the `--exclude-dir` option. For example, say you want to find out which files are using a certain piece of code on a JavaScript project; for multiple directories, specify the option multiple times.

[source,console]
----
$ grep "console.log" -r --exclude-dir="node_modules" --exclude-dir=".git" --exclude-dir="dist" .
----

