= Using OpenSSL
D10f <devontheroof@pm.me>
v0.1, 2024-01-24
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:icons: font
:description: using openssl
:keywords: openssl networking certificates cryptography rsa ec ed harmoush
:technologies: shell linux
:source-highlighter: pygments
:toc:

OpenSSL is a cryptography toolkit implementing the Secure Sockets Layer (SSL v2/v3) and Transport Layer Security (TLS v1) network protocols and related cryptography standards required by them.

== Disclaimer

The content of this post is largely based on the content produced by Ed Harmoush in his course, https://classes.pracnet.net/courses/openssl-training[OpenSSL Training].

You can find more information about Ed's courses in his https://pracnet.net[blog], as well as additional content on his https://www.youtube.com/channel/UCKmU-GKiukM8LYjkJFb8oBQ[YouTube channel].

== Asymmetric Cryptography

Also referred to as public cryptography, asymmetric cryptography uses values or _keys_ that are safe to share publicly over an insecure network while retaining the three core principles of integrity, confidentiality and authentication.

=== RSA

Is one of the most popular asymmetric encryption algorithms, named after the last names of their creators, Ron Rivest, Adi Shamir and Leonard Adleman, in 1977. It works by creating a pair of mathematically related _keys_, such that one key is used to encrypt a message while the other can decrypt it.

To generate a new key-pair:

[source,console]
----
$ openssl genrsa -out KEY.pem 2048
----

By default, `openssl genrsa` already produces the keys of 2048 bit length, but you could specify this value at the end of the command. There's a configuration file that can be modified to update this default value &mdash; as well as other settings &mdash; found at `/etc/openssl/openssl.conf`.

WARNING: As of this writing, 2048-bit key lengths is still considered reasonably secure. However, it's already projected that this won't be enough by the year 2030.

This produces a PEM-formatted file, which is a base64-encoded representation of the binary data that makes up the key. One advantage of this format is how easy it is to work with, generally, particularly for things like copy/paste.

If we inspect the contents of this file:

[source,console]
----
$ openssl rsa -in KEY.pem -noout -text
----

The `-in` argument takes the file to read, `-text` produces a human-readable, plain text representation and `-noout` prevents additional output in the original, base64-encoded format to be included. This command will output the various components involved in the RSA keys. The *modulus* and *publicExponent* combined are the values used for the _public_ key, while the *privateExponent* and the other values are used for the _private key_.

=== Elliptic Curve

Elliptic curve cryptography follows the same principle as RSA of using a key-pair, but the mathematics behind it are different. In essence, it's a more efficient way of doing the same thing, allowing for smaller key sizes while retaining the same level of security.

IMPORTANT: Security is a relative term. Something that is considered secure by today's standards may not be so in the next 10 years. In addition, security needs to be used within a context, and balanced with convenience. We could use massive key sizes all the time but that would make user experience needlessly detrimental, due to the long computation times.

To generate 

[source,console]
----
$ openssl genparam -algorithm EC -pkeyopt ec_paramgen_curve:secp384r1 -out EC-PARAM.pem
----

=== DSA

Digital Signature Algorithm. Used for signing and verifying signatures.

.Generate DSA Parameters File.
[source,console]
----
$ openssl dsparam -out DSA-PARAM.pem 1024
----

.Generate DSA Key file with Parameters File.
[source,console]
----
$ openssl gendsa -out DSA-KEY.pem DSA-PARAM.pem
----

.Generate DSA Parameters and Keys in one File.
[source,console]
----
$ openssl dsaparam -genkey -out DSA-PARAM-KEY.pem 2048
----

== Certificates

=== PEM Format

The PEM format...

=== Generating Certificates

[source,console]
----
$ openssl req -new -key KEY.pem -out CSR.pem
----

=== Self-Signed Certificates

Self-signed certificates are certificates that have been signed by the same public/private key-pair...

=== Inspecting Certificates

...
