= Read The Hostname From Within A Docker Container
D10f <devontheroof@pm.me>
v0.1, 2022-12-13
:license-url: https://creativecommons.org/licenses/by-sa/4.0/
:license-title: CC BY-SA 4.0
:doctype: article
:description: Use Go template syntax with Docker deployments to get information about the host in which a Docker container is deployed.
:keywords: docker swarm telegraf grafana templates container
:technologies: docker
:source-highlighter: pygments
:icons: font
:toc:

When deploying services using Docker Swarm, it's up to the orchestrator engine to decide where containers will be deployed. On a single node it's easy to predict in advanced the host, and we can work with some assumptions. However, on more than one node this becomes a little more difficult.

== Problem Statement

You have set up a fleet of hosts running Docker Swarm, on top of which you can now run various containerized applications. To monitor the health of the hosts you want to run metric collection software such as Telegraf, InfluxDB and Grafana.

You take advantage of the fact that your fleet already spawns multiple hosts and has an orchestrator taking over the deployment of individual containers, and you write compose file to make things easier for yourself. +
Unfortunately, when you check the dashboard you see that while the data points are correctly being reported, the hostnames correspond to the individual Docker container IDs, instead of the actual hosts that you care to monitor. This makes it difficult to distinguish which hosts are under more or less load.

== Initial Setup

This is the initial setup that worked fine except with the mentioned issue (excerpt of the service in question):

[source,yaml,title="docker-compose.yml"]
----
---
version: "3.8"

services:
    telegraf:
        image: telegraf:1.21
        deploy:
            mode: global
            placement:
                max_replicas_per_node: 1
            restart_policy:
                delay: 10s
        environment:
            HOST_ETC: /hostfs/etc
            HOST_PROC: /hostfs/proc
            HOST_SYS: /hostfs/sys
            HOST_VAR: /hostfs/var
            HOST_RUN: /hostfs/run
            HOST_MOUNT_PREFIX: /hostfs
        configs:
            - source: telegraf_config-cc3322b4
              target: /etc/telegraf/telegraf.conf
              mode: 0400
        volumes:
            - /:/hostfs:ro
        networks:
            - influxdb
----

As per the https://docs.influxdata.com/telegraf/v1.21/administration/configuration/#agent-configuration[Telegraf documentation], the hostname field can be left blank in order to default to the current hostname:

[source,ini,title="telegraf.conf"]
----
[agent]
    interval = "10s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "0s"
    flush_interval = "10s"
    flush_jitter = "0s"
    precision = "0s"
    hostname = "" # <1>
    omit_hostname = false

[[outputs.influxdb]]
    urls = ["http://influxdb:8086"]
    timeout = "5s"
    database = "telegraf"
    username = "telegraf"
    password = "XXXXXXXXXXXXXXXXXXXXX"
----
<1> Hostname left blank on purpose.

However, the way it works is by invoking Go's `os.Hostname` function to populate the field, which reads directly from `/proc/sys/kernel/hostname`. It would be reasonable to assume that, after mounting the entire `/hostfs/proc` to the container, this information would be available. Unfortunately this is not the case and the hostname that is reported is the ID of the Docker container in which it runs.

== Docker Service Templates

The solution is pretty straight forward, once you know the answer. Turns out, https://docs.docker.com/reference/cli/docker/service/create/#create-services-using-templates[Compose files support Go Templates], which we can use as a placeholder for various fields, including the hostname:

[source,yaml,title="docker-compose.yml"]
----
---
version: "3.8"

services:
    telegraf:
        image: telegraf:1.21
        hostname: "{{.Node.Hostname}}" # [!code ++]
        deploy:
            mode: global
            placement:
                max_replicas_per_node: 1
            restart_policy:
                delay: 10s
        environment:
            HOST_ETC: /hostfs/etc
            HOST_PROC: /hostfs/proc
            HOST_SYS: /hostfs/sys
            HOST_VAR: /hostfs/var
            HOST_RUN: /hostfs/run
            HOST_MOUNT_PREFIX: /hostfs
        configs:
            - source: telegraf_config-cc3322b4
              target: /etc/telegraf/telegraf.conf
              mode: 0400
        volumes:
            - /:/hostfs:ro
        networks:
            - influxdb
----

This way, the variable gets interpolated whenever the container is deployed, reporting the correct hostname for each container instance and showing it correctly in the Grafana dashboard.
